parameters:
    security.authentication.success_handler:
        class: AppBundle\Handler\AuthenticationSuccessHandler
        arguments: [@security.http_utils, @translator]
    security.authentication.failure_handler:
        class: AppBundle\Handler\AuthenticationFailureHandler
        tag: @monolog.logger
        arguments: [@http_kernel, @security.http_utils, @translator]

#<container xmlns="http://symfony.com/schema/dic/services"
#    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
#
#    <parameters>
#        <parameter key="security.authentication.success_handler.class">Tecnocreaciones\Bundle\AjaxFOSUserBundle\Handler\AuthenticationSuccessHandler</parameter>
#        <parameter key="security.authentication.failure_handler.class">Tecnocreaciones\Bundle\AjaxFOSUserBundle\Handler\AuthenticationFailureHandler</parameter>
#    </parameters>
#
#    <services>
#        <service id="security.authentication.success_handler" class="%security.authentication.success_handler.class%" abstract="true" public="false">
#            <argument type="service" id="security.http_utils" />
#            <argument type="collection" /> <!-- Options -->
#            <call method="setTranslator">
#                <argument  type="service" id="translator" />
#            </call>
#        </service>
#
#        <service id="security.authentication.failure_handler" class="%security.authentication.failure_handler.class%" abstract="true" public="false">
#            <tag name="monolog.logger" channel="security" />
#            <argument type="service" id="http_kernel" />
#            <argument type="service" id="security.http_utils" />
#            <argument type="collection" /> <!-- Options -->
#            <argument type="service" id="logger" on-invalid="null" />
#            <call method="setTranslator">
#                <argument  type="service" id="translator" />
#            </call>
#        </service>
#
#    </services>
#</container>